id: PBA2FAE7E
initial_creation_type: input
source_metadata:
  title: Jātaka Series
  language: en
  description: 'Texts related to tales of the Buddha''s previous lives (jātaka; skyes
    rabs):'
  volume:
    110bdf1b541541518c3077d1c001bde6:
      title: How Our Supreme Teacher Generated Bodhicitta and Other Topics
      parent: History
    fd60451ef39a4bc2bef82da809a00606:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
created_at: '2022-03-01T04:00:32.934748'
last_modified_at: '2022-03-01T04:00:32.934756'
